### ISSUE TITLE
TerseDecompress incubation renewal

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#103]
TerseDecompress is up for incubation renewal, at it was approved 2019-01-01

**Comment by jmertic** [comment]
From previous TAC discussion, looking for insight from @egelerkl on status and progress towards graduation.

**Comment by jmertic** [comment]
TAC indicated that this should move to Emeritus if no action by the next TAC meeting.

**Comment by jmertic** [comment]
@PeterFandelAtRocket Will follow up

**Comment by jmertic** [comment]
TAC requests to find a new maintainer before next TAC meeting.

**Comment by jmertic** [comment]
@PeterFandelAtRocket is trying to connect with @egelerkl to determine status. @jmertic also has made a call for a new maintainer.

**Comment by jmertic** [comment]
The TAC has requested to hold a vote to move this project into Emeritus status. There has since been interest raised by @andrew890 in maintaining this code, so in light of that I'm working with the TAC to determine if the vote should be paused.

**Comment by hogstrom** [comment]
Ia there a list of proposed enhancements?

Matt Hogstrom
PGP key 0F143BC1

**Comment by andrew890** [comment]
The change I want to make is to support binary variable length records, i.e. output binary data with RDWs. I have forked the repository and have been doing some work. So far all I have done is refactoring to try to understand the code.

Refactoring is difficult to coordinate with any other people's changes because it becomes difficult to merge changes. I was hoping to contact the owners to see whether they are interested in incorporating the changes, or whether I was best to go independently.

From my point of view I am happy to continue with the changes for my own purposes in my own repo. There could be value in merging it back into the original, although changes are always more complicated if they need to be generally available.

The main problem I anticipate is that I don't really understand the decompression code i.e. the core functionality. It is questionable whether I would be able to be of any assistance if there was a bug or modifications needed to that part of the code.

**Comment by jmertic** [comment]
@andrew890 Can you chime in on your interests in maintain the project?

**Comment by andrew890** [comment]
I have been working on some changes that would be useful to be merged back into the Open Mainframe Project version.
Alternatively I can make them available independently, but multiple forks of the same software is not ideal.
So I am willing to maintain it to incorporate my changes into the OMP version.
It would be preferable to have someone else reviewing the changes that I want to introduce, rather than having me do it myself, but I understand that there is no-one else available.

**Comment by jmertic** [comment]
@andrew890 has agreed to be maintainer. Will provide access.

**Comment by jmertic** [comment]
TAC to consider incubation renewal after transition.

**Comment by jmertic** [comment]
Ingo to be TAC sponsor

**Comment by jmertic** [comment]
@andrew890 - Are you ready to come back to the TAC with an update on this project for consideration to extend it's incubation status?

**Comment by jmertic** [comment]
@andrew890 Let us know if you are able to present to the TAC tomorrow

**Comment by jmertic** [comment]
@andrew890 Could we schedule this out of band from a normal TAC meeting - there is a lot of interest in this project status.

**Comment by jmertic** [comment]
@andrew890 This project was moved to Emeritus by vote of the TAC. More details on Emeritus stage at https://tac.openmainframeproject.org/process/project_stages.html#emeritus-stage

https://github.com/openmainframeproject/omp-landscape/pull/539
