### ISSUE TITLE
Incubation Renewal - Software Discovery Tool

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#189]
Renewal date 4/9/2021

**Comment by jmertic** [comment]
@pleia2 @jbostian Friendly note that this project is up for annual review at the next TAC meeting. Let me know if you have questions/concerns.

**Comment by pleia2** [comment]
Acknowledged. I've added this to our meeting agenda this week and will let you know if we have any questions.

**Comment by pleia2** [comment]
We had a very slow start due to logistical problems with the project we forked from, but achieved the following of note:

 - Consensus on forking PDS and software architecture for moving forward to separate code from data sources
 - Migrated the original PDS project from Python 2 to Python 3
 - Completed fork of the code in early 2021, and currently working on:
   - Fixes to bugs introduced with the fork
   - Licensing cleanup
   - Improvements to the documentation
 - We're also reaching out to community members in the broader mainframe ecosystem to see what they're looking for in the tool feature-wise
 - Some work has been done to do some UI improvements (not yet in a public branch, but soon!).
 - We have engaged two mentees from the Mentorship program! Projects are in place:
   - Add a z/OS section to the search
   - Add an accompanying source file of open source projects for z/OS
   - A stretch goal of creating an API for programmatic querying of the data sources

Work so far has been done by 3 IBM employees and a student from Indian Institue of Technology Kanpur (who will also be joining us as a mentee)

I'm confident that with our current momentum we will be able to make great progress towards graduation in the coming year.

**Comment by jmertic** [comment]
Approved by TAC on 2021-05-13.
