### ISSUE TITLE
Ambitus annual review 7/14

### ISSUE THREAD

**Issue by jmertic** [openmainframeproject/tac#358]
@jabostian @jbostian Let us know if you are ready for the review /cc @yarille

**Comment by jbostian** [comment]
I could use another month to get my ducks in a row for the Ambitus project before it’s ready for consideration as an active project.  If we want to review tomorrow, it’ll have to be for Ambitus as an incubator project for another year.

--------
Kind Regards / Mit freundlichen Grüßen / Cordialmente
***@***.***   (Joe)
IBM z Systems, Open Source and Analytics Architect


From: John Mertic ***@***.***>
Date: Tuesday, June 7, 2022 at 5:13 PM
To: openmainframeproject/tac ***@***.***>
Cc: Joseph Bostian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [openmainframeproject/tac] Ambitus annual review 6/9 (Issue #358)
@jabostian @jbostian Let us know if you are ready for the review /cc @yarille — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: <openmainframeproject/tac/issues/358
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@jabostian<https://github.com/jabostian> @jbostian<https://github.com/jbostian> Let us know if you are ready for the review /cc @yarille<https://github.com/yarille>

**Comment by jmertic** [comment]
That seems good for me. I'll make the adjustment and have you on 7/14.

Adding @Yarille Kilborn ***@***.***> for awareness.

**Comment by yarille** [comment]
Approved for renewal by email vote.
